//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18047.
// 
#pragma warning disable 1591

namespace OpcXmlDaClient.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service", Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(float[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(int[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(uint[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(long[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ulong[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(double[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ushort[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(bool[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(string[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(System.DateTime[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(decimal[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sbyte[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(short[]))]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadOperationCompleted;
        
        private System.Threading.SendOrPostCallback WriteOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubscribeOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubscriptionPolledRefreshOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubscriptionCancelOperationCompleted;
        
        private System.Threading.SendOrPostCallback BrowseOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPropertiesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetStatusCompletedEventHandler GetStatusCompleted;
        
        /// <remarks/>
        public event ReadCompletedEventHandler ReadCompleted;
        
        /// <remarks/>
        public event WriteCompletedEventHandler WriteCompleted;
        
        /// <remarks/>
        public event SubscribeCompletedEventHandler SubscribeCompleted;
        
        /// <remarks/>
        public event SubscriptionPolledRefreshCompletedEventHandler SubscriptionPolledRefreshCompleted;
        
        /// <remarks/>
        public event SubscriptionCancelCompletedEventHandler SubscriptionCancelCompleted;
        
        /// <remarks/>
        public event BrowseCompletedEventHandler BrowseCompleted;
        
        /// <remarks/>
        public event GetPropertiesCompletedEventHandler GetPropertiesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://opcfoundation.org/webservices/XMLDA/1.0/GetStatus", RequestNamespace="http://opcfoundation.org/webservices/XMLDA/1.0/", ResponseNamespace="http://opcfoundation.org/webservices/XMLDA/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReplyBase GetStatus([System.Xml.Serialization.XmlAttributeAttribute()] string LocaleID, [System.Xml.Serialization.XmlAttributeAttribute()] string ClientRequestHandle, out ServerStatus Status) {
            object[] results = this.Invoke("GetStatus", new object[] {
                        LocaleID,
                        ClientRequestHandle});
            Status = ((ServerStatus)(results[1]));
            return ((ReplyBase)(results[0]));
        }
        
        /// <remarks/>
        public void GetStatusAsync(string LocaleID, string ClientRequestHandle) {
            this.GetStatusAsync(LocaleID, ClientRequestHandle, null);
        }
        
        /// <remarks/>
        public void GetStatusAsync(string LocaleID, string ClientRequestHandle, object userState) {
            if ((this.GetStatusOperationCompleted == null)) {
                this.GetStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStatusOperationCompleted);
            }
            this.InvokeAsync("GetStatus", new object[] {
                        LocaleID,
                        ClientRequestHandle}, this.GetStatusOperationCompleted, userState);
        }
        
        private void OnGetStatusOperationCompleted(object arg) {
            if ((this.GetStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStatusCompleted(this, new GetStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://opcfoundation.org/webservices/XMLDA/1.0/Read", RequestNamespace="http://opcfoundation.org/webservices/XMLDA/1.0/", ResponseNamespace="http://opcfoundation.org/webservices/XMLDA/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReplyBase Read(RequestOptions Options, ReadRequestItemList ItemList, out ReplyItemList RItemList, [System.Xml.Serialization.XmlElementAttribute("Errors")] out OPCError[] Errors) {
            object[] results = this.Invoke("Read", new object[] {
                        Options,
                        ItemList});
            RItemList = ((ReplyItemList)(results[1]));
            Errors = ((OPCError[])(results[2]));
            return ((ReplyBase)(results[0]));
        }
        
        /// <remarks/>
        public void ReadAsync(RequestOptions Options, ReadRequestItemList ItemList) {
            this.ReadAsync(Options, ItemList, null);
        }
        
        /// <remarks/>
        public void ReadAsync(RequestOptions Options, ReadRequestItemList ItemList, object userState) {
            if ((this.ReadOperationCompleted == null)) {
                this.ReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOperationCompleted);
            }
            this.InvokeAsync("Read", new object[] {
                        Options,
                        ItemList}, this.ReadOperationCompleted, userState);
        }
        
        private void OnReadOperationCompleted(object arg) {
            if ((this.ReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCompleted(this, new ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://opcfoundation.org/webservices/XMLDA/1.0/Write", RequestNamespace="http://opcfoundation.org/webservices/XMLDA/1.0/", ResponseNamespace="http://opcfoundation.org/webservices/XMLDA/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReplyBase Write(RequestOptions Options, WriteRequestItemList ItemList, [System.Xml.Serialization.XmlAttributeAttribute()] bool ReturnValuesOnReply, out ReplyItemList RItemList, [System.Xml.Serialization.XmlElementAttribute("Errors")] out OPCError[] Errors) {
            object[] results = this.Invoke("Write", new object[] {
                        Options,
                        ItemList,
                        ReturnValuesOnReply});
            RItemList = ((ReplyItemList)(results[1]));
            Errors = ((OPCError[])(results[2]));
            return ((ReplyBase)(results[0]));
        }
        
        /// <remarks/>
        public void WriteAsync(RequestOptions Options, WriteRequestItemList ItemList, bool ReturnValuesOnReply) {
            this.WriteAsync(Options, ItemList, ReturnValuesOnReply, null);
        }
        
        /// <remarks/>
        public void WriteAsync(RequestOptions Options, WriteRequestItemList ItemList, bool ReturnValuesOnReply, object userState) {
            if ((this.WriteOperationCompleted == null)) {
                this.WriteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWriteOperationCompleted);
            }
            this.InvokeAsync("Write", new object[] {
                        Options,
                        ItemList,
                        ReturnValuesOnReply}, this.WriteOperationCompleted, userState);
        }
        
        private void OnWriteOperationCompleted(object arg) {
            if ((this.WriteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WriteCompleted(this, new WriteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://opcfoundation.org/webservices/XMLDA/1.0/Subscribe", RequestNamespace="http://opcfoundation.org/webservices/XMLDA/1.0/", ResponseNamespace="http://opcfoundation.org/webservices/XMLDA/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReplyBase Subscribe(RequestOptions Options, SubscribeRequestItemList ItemList, [System.Xml.Serialization.XmlAttributeAttribute()] bool ReturnValuesOnReply, [System.Xml.Serialization.XmlAttributeAttribute()] [System.ComponentModel.DefaultValueAttribute(0)] int SubscriptionPingRate, out SubscribeReplyItemList RItemList, [System.Xml.Serialization.XmlElementAttribute("Errors")] out OPCError[] Errors, [System.Xml.Serialization.XmlAttributeAttribute()] out string ServerSubHandle) {
            object[] results = this.Invoke("Subscribe", new object[] {
                        Options,
                        ItemList,
                        ReturnValuesOnReply,
                        SubscriptionPingRate});
            RItemList = ((SubscribeReplyItemList)(results[1]));
            Errors = ((OPCError[])(results[2]));
            ServerSubHandle = ((string)(results[3]));
            return ((ReplyBase)(results[0]));
        }
        
        /// <remarks/>
        public void SubscribeAsync(RequestOptions Options, SubscribeRequestItemList ItemList, bool ReturnValuesOnReply, int SubscriptionPingRate) {
            this.SubscribeAsync(Options, ItemList, ReturnValuesOnReply, SubscriptionPingRate, null);
        }
        
        /// <remarks/>
        public void SubscribeAsync(RequestOptions Options, SubscribeRequestItemList ItemList, bool ReturnValuesOnReply, int SubscriptionPingRate, object userState) {
            if ((this.SubscribeOperationCompleted == null)) {
                this.SubscribeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubscribeOperationCompleted);
            }
            this.InvokeAsync("Subscribe", new object[] {
                        Options,
                        ItemList,
                        ReturnValuesOnReply,
                        SubscriptionPingRate}, this.SubscribeOperationCompleted, userState);
        }
        
        private void OnSubscribeOperationCompleted(object arg) {
            if ((this.SubscribeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubscribeCompleted(this, new SubscribeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://opcfoundation.org/webservices/XMLDA/1.0/SubscriptionPolledRefresh", RequestNamespace="http://opcfoundation.org/webservices/XMLDA/1.0/", ResponseNamespace="http://opcfoundation.org/webservices/XMLDA/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReplyBase SubscriptionPolledRefresh(RequestOptions Options, [System.Xml.Serialization.XmlElementAttribute("ServerSubHandles")] string[] ServerSubHandles, [System.Xml.Serialization.XmlAttributeAttribute()] System.DateTime HoldTime, [System.Xml.Serialization.XmlAttributeAttribute()] [System.Xml.Serialization.XmlIgnoreAttribute()] bool HoldTimeSpecified, [System.Xml.Serialization.XmlAttributeAttribute()] [System.ComponentModel.DefaultValueAttribute(0)] int WaitTime, [System.Xml.Serialization.XmlAttributeAttribute()] [System.ComponentModel.DefaultValueAttribute(false)] bool ReturnAllItems, [System.Xml.Serialization.XmlElementAttribute("InvalidServerSubHandles")] out string[] InvalidServerSubHandles, [System.Xml.Serialization.XmlElementAttribute("RItemList")] out SubscribePolledRefreshReplyItemList[] RItemList, [System.Xml.Serialization.XmlElementAttribute("Errors")] out OPCError[] Errors, [System.Xml.Serialization.XmlAttributeAttribute()] [System.ComponentModel.DefaultValueAttribute(false)] out bool DataBufferOverflow) {
            object[] results = this.Invoke("SubscriptionPolledRefresh", new object[] {
                        Options,
                        ServerSubHandles,
                        HoldTime,
                        HoldTimeSpecified,
                        WaitTime,
                        ReturnAllItems});
            InvalidServerSubHandles = ((string[])(results[1]));
            RItemList = ((SubscribePolledRefreshReplyItemList[])(results[2]));
            Errors = ((OPCError[])(results[3]));
            DataBufferOverflow = ((bool)(results[4]));
            return ((ReplyBase)(results[0]));
        }
        
        /// <remarks/>
        public void SubscriptionPolledRefreshAsync(RequestOptions Options, string[] ServerSubHandles, System.DateTime HoldTime, bool HoldTimeSpecified, int WaitTime, bool ReturnAllItems) {
            this.SubscriptionPolledRefreshAsync(Options, ServerSubHandles, HoldTime, HoldTimeSpecified, WaitTime, ReturnAllItems, null);
        }
        
        /// <remarks/>
        public void SubscriptionPolledRefreshAsync(RequestOptions Options, string[] ServerSubHandles, System.DateTime HoldTime, bool HoldTimeSpecified, int WaitTime, bool ReturnAllItems, object userState) {
            if ((this.SubscriptionPolledRefreshOperationCompleted == null)) {
                this.SubscriptionPolledRefreshOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubscriptionPolledRefreshOperationCompleted);
            }
            this.InvokeAsync("SubscriptionPolledRefresh", new object[] {
                        Options,
                        ServerSubHandles,
                        HoldTime,
                        HoldTimeSpecified,
                        WaitTime,
                        ReturnAllItems}, this.SubscriptionPolledRefreshOperationCompleted, userState);
        }
        
        private void OnSubscriptionPolledRefreshOperationCompleted(object arg) {
            if ((this.SubscriptionPolledRefreshCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubscriptionPolledRefreshCompleted(this, new SubscriptionPolledRefreshCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://opcfoundation.org/webservices/XMLDA/1.0/SubscriptionCancel", RequestNamespace="http://opcfoundation.org/webservices/XMLDA/1.0/", ResponseNamespace="http://opcfoundation.org/webservices/XMLDA/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SubscriptionCancel([System.Xml.Serialization.XmlAttributeAttribute()] string ServerSubHandle, [System.Xml.Serialization.XmlAttributeAttribute()] ref string ClientRequestHandle) {
            object[] results = this.Invoke("SubscriptionCancel", new object[] {
                        ServerSubHandle,
                        ClientRequestHandle});
            ClientRequestHandle = ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SubscriptionCancelAsync(string ServerSubHandle, string ClientRequestHandle) {
            this.SubscriptionCancelAsync(ServerSubHandle, ClientRequestHandle, null);
        }
        
        /// <remarks/>
        public void SubscriptionCancelAsync(string ServerSubHandle, string ClientRequestHandle, object userState) {
            if ((this.SubscriptionCancelOperationCompleted == null)) {
                this.SubscriptionCancelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubscriptionCancelOperationCompleted);
            }
            this.InvokeAsync("SubscriptionCancel", new object[] {
                        ServerSubHandle,
                        ClientRequestHandle}, this.SubscriptionCancelOperationCompleted, userState);
        }
        
        private void OnSubscriptionCancelOperationCompleted(object arg) {
            if ((this.SubscriptionCancelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubscriptionCancelCompleted(this, new SubscriptionCancelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://opcfoundation.org/webservices/XMLDA/1.0/Browse", RequestNamespace="http://opcfoundation.org/webservices/XMLDA/1.0/", ResponseNamespace="http://opcfoundation.org/webservices/XMLDA/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReplyBase Browse(
                    [System.Xml.Serialization.XmlElementAttribute("PropertyNames")] System.Xml.XmlQualifiedName[] PropertyNames, 
                    [System.Xml.Serialization.XmlAttributeAttribute()] string LocaleID, 
                    [System.Xml.Serialization.XmlAttributeAttribute()] string ClientRequestHandle, 
                    [System.Xml.Serialization.XmlAttributeAttribute()] string ItemPath, 
                    [System.Xml.Serialization.XmlAttributeAttribute()] string ItemName, 
                    [System.Xml.Serialization.XmlAttributeAttribute()] ref string ContinuationPoint, 
                    [System.Xml.Serialization.XmlAttributeAttribute()] [System.ComponentModel.DefaultValueAttribute(0)] int MaxElementsReturned, 
                    [System.Xml.Serialization.XmlAttributeAttribute()] [System.ComponentModel.DefaultValueAttribute(browseFilter.all)] browseFilter BrowseFilter, 
                    [System.Xml.Serialization.XmlAttributeAttribute()] string ElementNameFilter, 
                    [System.Xml.Serialization.XmlAttributeAttribute()] string VendorFilter, 
                    [System.Xml.Serialization.XmlAttributeAttribute()] [System.ComponentModel.DefaultValueAttribute(false)] bool ReturnAllProperties, 
                    [System.Xml.Serialization.XmlAttributeAttribute()] [System.ComponentModel.DefaultValueAttribute(false)] bool ReturnPropertyValues, 
                    [System.Xml.Serialization.XmlAttributeAttribute()] [System.ComponentModel.DefaultValueAttribute(false)] bool ReturnErrorText, 
                    [System.Xml.Serialization.XmlElementAttribute("Elements")] out BrowseElement[] Elements, 
                    [System.Xml.Serialization.XmlElementAttribute("Errors")] out OPCError[] Errors, 
                    [System.Xml.Serialization.XmlAttributeAttribute()] [System.ComponentModel.DefaultValueAttribute(false)] out bool MoreElements) {
            object[] results = this.Invoke("Browse", new object[] {
                        PropertyNames,
                        LocaleID,
                        ClientRequestHandle,
                        ItemPath,
                        ItemName,
                        ContinuationPoint,
                        MaxElementsReturned,
                        BrowseFilter,
                        ElementNameFilter,
                        VendorFilter,
                        ReturnAllProperties,
                        ReturnPropertyValues,
                        ReturnErrorText});
            ContinuationPoint = ((string)(results[1]));
            Elements = ((BrowseElement[])(results[2]));
            Errors = ((OPCError[])(results[3]));
            MoreElements = ((bool)(results[4]));
            return ((ReplyBase)(results[0]));
        }
        
        /// <remarks/>
        public void BrowseAsync(System.Xml.XmlQualifiedName[] PropertyNames, string LocaleID, string ClientRequestHandle, string ItemPath, string ItemName, string ContinuationPoint, int MaxElementsReturned, browseFilter BrowseFilter, string ElementNameFilter, string VendorFilter, bool ReturnAllProperties, bool ReturnPropertyValues, bool ReturnErrorText) {
            this.BrowseAsync(PropertyNames, LocaleID, ClientRequestHandle, ItemPath, ItemName, ContinuationPoint, MaxElementsReturned, BrowseFilter, ElementNameFilter, VendorFilter, ReturnAllProperties, ReturnPropertyValues, ReturnErrorText, null);
        }
        
        /// <remarks/>
        public void BrowseAsync(System.Xml.XmlQualifiedName[] PropertyNames, string LocaleID, string ClientRequestHandle, string ItemPath, string ItemName, string ContinuationPoint, int MaxElementsReturned, browseFilter BrowseFilter, string ElementNameFilter, string VendorFilter, bool ReturnAllProperties, bool ReturnPropertyValues, bool ReturnErrorText, object userState) {
            if ((this.BrowseOperationCompleted == null)) {
                this.BrowseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBrowseOperationCompleted);
            }
            this.InvokeAsync("Browse", new object[] {
                        PropertyNames,
                        LocaleID,
                        ClientRequestHandle,
                        ItemPath,
                        ItemName,
                        ContinuationPoint,
                        MaxElementsReturned,
                        BrowseFilter,
                        ElementNameFilter,
                        VendorFilter,
                        ReturnAllProperties,
                        ReturnPropertyValues,
                        ReturnErrorText}, this.BrowseOperationCompleted, userState);
        }
        
        private void OnBrowseOperationCompleted(object arg) {
            if ((this.BrowseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BrowseCompleted(this, new BrowseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://opcfoundation.org/webservices/XMLDA/1.0/GetProperties", RequestNamespace="http://opcfoundation.org/webservices/XMLDA/1.0/", ResponseNamespace="http://opcfoundation.org/webservices/XMLDA/1.0/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReplyBase GetProperties([System.Xml.Serialization.XmlElementAttribute("ItemIDs")] ItemIdentifier[] ItemIDs, [System.Xml.Serialization.XmlElementAttribute("PropertyNames")] System.Xml.XmlQualifiedName[] PropertyNames, [System.Xml.Serialization.XmlAttributeAttribute()] string LocaleID, [System.Xml.Serialization.XmlAttributeAttribute()] string ClientRequestHandle, [System.Xml.Serialization.XmlAttributeAttribute()] string ItemPath, [System.Xml.Serialization.XmlAttributeAttribute()] [System.ComponentModel.DefaultValueAttribute(false)] bool ReturnAllProperties, [System.Xml.Serialization.XmlAttributeAttribute()] [System.ComponentModel.DefaultValueAttribute(false)] bool ReturnPropertyValues, [System.Xml.Serialization.XmlAttributeAttribute()] [System.ComponentModel.DefaultValueAttribute(false)] bool ReturnErrorText, [System.Xml.Serialization.XmlElementAttribute("PropertyLists")] out PropertyReplyList[] PropertyLists, [System.Xml.Serialization.XmlElementAttribute("Errors")] out OPCError[] Errors) {
            object[] results = this.Invoke("GetProperties", new object[] {
                        ItemIDs,
                        PropertyNames,
                        LocaleID,
                        ClientRequestHandle,
                        ItemPath,
                        ReturnAllProperties,
                        ReturnPropertyValues,
                        ReturnErrorText});
            PropertyLists = ((PropertyReplyList[])(results[1]));
            Errors = ((OPCError[])(results[2]));
            return ((ReplyBase)(results[0]));
        }
        
        /// <remarks/>
        public void GetPropertiesAsync(ItemIdentifier[] ItemIDs, System.Xml.XmlQualifiedName[] PropertyNames, string LocaleID, string ClientRequestHandle, string ItemPath, bool ReturnAllProperties, bool ReturnPropertyValues, bool ReturnErrorText) {
            this.GetPropertiesAsync(ItemIDs, PropertyNames, LocaleID, ClientRequestHandle, ItemPath, ReturnAllProperties, ReturnPropertyValues, ReturnErrorText, null);
        }
        
        /// <remarks/>
        public void GetPropertiesAsync(ItemIdentifier[] ItemIDs, System.Xml.XmlQualifiedName[] PropertyNames, string LocaleID, string ClientRequestHandle, string ItemPath, bool ReturnAllProperties, bool ReturnPropertyValues, bool ReturnErrorText, object userState) {
            if ((this.GetPropertiesOperationCompleted == null)) {
                this.GetPropertiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPropertiesOperationCompleted);
            }
            this.InvokeAsync("GetProperties", new object[] {
                        ItemIDs,
                        PropertyNames,
                        LocaleID,
                        ClientRequestHandle,
                        ItemPath,
                        ReturnAllProperties,
                        ReturnPropertyValues,
                        ReturnErrorText}, this.GetPropertiesOperationCompleted, userState);
        }
        
        private void OnGetPropertiesOperationCompleted(object arg) {
            if ((this.GetPropertiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPropertiesCompleted(this, new GetPropertiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
    public partial class ReplyBase {
        
        private System.DateTime rcvTimeField;
        
        private System.DateTime replyTimeField;
        
        private string clientRequestHandleField;
        
        private string revisedLocaleIDField;
        
        private serverState serverStateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime RcvTime {
            get {
                return this.rcvTimeField;
            }
            set {
                this.rcvTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime ReplyTime {
            get {
                return this.replyTimeField;
            }
            set {
                this.replyTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ClientRequestHandle {
            get {
                return this.clientRequestHandleField;
            }
            set {
                this.clientRequestHandleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RevisedLocaleID {
            get {
                return this.revisedLocaleIDField;
            }
            set {
                this.revisedLocaleIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public serverState ServerState {
            get {
                return this.serverStateField;
            }
            set {
                this.serverStateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
    public enum serverState {
        
        /// <remarks/>
        running,
        
        /// <remarks/>
        failed,
        
        /// <remarks/>
        noConfig,
        
        /// <remarks/>
        suspended,
        
        /// <remarks/>
        test,
        
        /// <remarks/>
        commFault,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
    public partial class PropertyReplyList {
        
        private ItemProperty[] propertiesField;
        
        private string itemPathField;
        
        private string itemNameField;
        
        private System.Xml.XmlQualifiedName resultIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Properties")]
        public ItemProperty[] Properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemPath {
            get {
                return this.itemPathField;
            }
            set {
                this.itemPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName ResultID {
            get {
                return this.resultIDField;
            }
            set {
                this.resultIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
    public partial class ItemProperty {
        
        private object valueField;
        
        private System.Xml.XmlQualifiedName nameField;
        
        private string descriptionField;
        
        private string itemPathField;
        
        private string itemNameField;
        
        private System.Xml.XmlQualifiedName resultIDField;
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemPath {
            get {
                return this.itemPathField;
            }
            set {
                this.itemPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName ResultID {
            get {
                return this.resultIDField;
            }
            set {
                this.resultIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
    public partial class ItemIdentifier {
        
        private string itemPathField;
        
        private string itemNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemPath {
            get {
                return this.itemPathField;
            }
            set {
                this.itemPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
    public partial class BrowseElement {
        
        private ItemProperty[] propertiesField;
        
        private string nameField;
        
        private string itemPathField;
        
        private string itemNameField;
        
        private bool isItemField;
        
        private bool hasChildrenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Properties")]
        public ItemProperty[] Properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemPath {
            get {
                return this.itemPathField;
            }
            set {
                this.itemPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsItem {
            get {
                return this.isItemField;
            }
            set {
                this.isItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool HasChildren {
            get {
                return this.hasChildrenField;
            }
            set {
                this.hasChildrenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
    public partial class SubscribePolledRefreshReplyItemList {
        
        private ItemValue[] itemsField;
        
        private string subscriptionHandleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items")]
        public ItemValue[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubscriptionHandle {
            get {
                return this.subscriptionHandleField;
            }
            set {
                this.subscriptionHandleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
    public partial class ItemValue {
        
        private string diagnosticInfoField;
        
        private object valueField;
        
        private OPCQuality qualityField;
        
        private System.Xml.XmlQualifiedName valueTypeQualifierField;
        
        private string itemPathField;
        
        private string itemNameField;
        
        private string clientItemHandleField;
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        private System.Xml.XmlQualifiedName resultIDField;
        
        /// <remarks/>
        public string DiagnosticInfo {
            get {
                return this.diagnosticInfoField;
            }
            set {
                this.diagnosticInfoField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public OPCQuality Quality {
            get {
                return this.qualityField;
            }
            set {
                this.qualityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName ValueTypeQualifier {
            get {
                return this.valueTypeQualifierField;
            }
            set {
                this.valueTypeQualifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemPath {
            get {
                return this.itemPathField;
            }
            set {
                this.itemPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ClientItemHandle {
            get {
                return this.clientItemHandleField;
            }
            set {
                this.clientItemHandleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName ResultID {
            get {
                return this.resultIDField;
            }
            set {
                this.resultIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
    public partial class OPCQuality {
        
        private qualityBits qualityFieldField;
        
        private limitBits limitFieldField;
        
        private byte vendorFieldField;
        
        public OPCQuality() {
            this.qualityFieldField = qualityBits.good;
            this.limitFieldField = limitBits.none;
            this.vendorFieldField = ((byte)(0));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(qualityBits.good)]
        public qualityBits QualityField {
            get {
                return this.qualityFieldField;
            }
            set {
                this.qualityFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(limitBits.none)]
        public limitBits LimitField {
            get {
                return this.limitFieldField;
            }
            set {
                this.limitFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(byte), "0")]
        public byte VendorField {
            get {
                return this.vendorFieldField;
            }
            set {
                this.vendorFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
    public enum qualityBits {
        
        /// <remarks/>
        bad,
        
        /// <remarks/>
        badConfigurationError,
        
        /// <remarks/>
        badNotConnected,
        
        /// <remarks/>
        badDeviceFailure,
        
        /// <remarks/>
        badSensorFailure,
        
        /// <remarks/>
        badLastKnownValue,
        
        /// <remarks/>
        badCommFailure,
        
        /// <remarks/>
        badOutOfService,
        
        /// <remarks/>
        badWaitingForInitialData,
        
        /// <remarks/>
        uncertain,
        
        /// <remarks/>
        uncertainLastUsableValue,
        
        /// <remarks/>
        uncertainSensorNotAccurate,
        
        /// <remarks/>
        uncertainEUExceeded,
        
        /// <remarks/>
        uncertainSubNormal,
        
        /// <remarks/>
        good,
        
        /// <remarks/>
        goodLocalOverride,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
    public enum limitBits {
        
        /// <remarks/>
        none,
        
        /// <remarks/>
        low,
        
        /// <remarks/>
        high,
        
        /// <remarks/>
        constant,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
    public partial class SubscribeItemValue {
        
        private ItemValue itemValueField;
        
        private int revisedSamplingRateField;
        
        private bool revisedSamplingRateFieldSpecified;
        
        /// <remarks/>
        public ItemValue ItemValue {
            get {
                return this.itemValueField;
            }
            set {
                this.itemValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int RevisedSamplingRate {
            get {
                return this.revisedSamplingRateField;
            }
            set {
                this.revisedSamplingRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RevisedSamplingRateSpecified {
            get {
                return this.revisedSamplingRateFieldSpecified;
            }
            set {
                this.revisedSamplingRateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
    public partial class SubscribeReplyItemList {
        
        private SubscribeItemValue[] itemsField;
        
        private int revisedSamplingRateField;
        
        private bool revisedSamplingRateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items")]
        public SubscribeItemValue[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int RevisedSamplingRate {
            get {
                return this.revisedSamplingRateField;
            }
            set {
                this.revisedSamplingRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RevisedSamplingRateSpecified {
            get {
                return this.revisedSamplingRateFieldSpecified;
            }
            set {
                this.revisedSamplingRateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
    public partial class SubscribeRequestItem {
        
        private string itemPathField;
        
        private System.Xml.XmlQualifiedName reqTypeField;
        
        private string itemNameField;
        
        private string clientItemHandleField;
        
        private float deadbandField;
        
        private bool deadbandFieldSpecified;
        
        private int requestedSamplingRateField;
        
        private bool requestedSamplingRateFieldSpecified;
        
        private bool enableBufferingField;
        
        private bool enableBufferingFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemPath {
            get {
                return this.itemPathField;
            }
            set {
                this.itemPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName ReqType {
            get {
                return this.reqTypeField;
            }
            set {
                this.reqTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ClientItemHandle {
            get {
                return this.clientItemHandleField;
            }
            set {
                this.clientItemHandleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Deadband {
            get {
                return this.deadbandField;
            }
            set {
                this.deadbandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeadbandSpecified {
            get {
                return this.deadbandFieldSpecified;
            }
            set {
                this.deadbandFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int RequestedSamplingRate {
            get {
                return this.requestedSamplingRateField;
            }
            set {
                this.requestedSamplingRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RequestedSamplingRateSpecified {
            get {
                return this.requestedSamplingRateFieldSpecified;
            }
            set {
                this.requestedSamplingRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool EnableBuffering {
            get {
                return this.enableBufferingField;
            }
            set {
                this.enableBufferingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnableBufferingSpecified {
            get {
                return this.enableBufferingFieldSpecified;
            }
            set {
                this.enableBufferingFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
    public partial class SubscribeRequestItemList {
        
        private SubscribeRequestItem[] itemsField;
        
        private string itemPathField;
        
        private System.Xml.XmlQualifiedName reqTypeField;
        
        private float deadbandField;
        
        private bool deadbandFieldSpecified;
        
        private int requestedSamplingRateField;
        
        private bool requestedSamplingRateFieldSpecified;
        
        private bool enableBufferingField;
        
        private bool enableBufferingFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items")]
        public SubscribeRequestItem[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemPath {
            get {
                return this.itemPathField;
            }
            set {
                this.itemPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName ReqType {
            get {
                return this.reqTypeField;
            }
            set {
                this.reqTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Deadband {
            get {
                return this.deadbandField;
            }
            set {
                this.deadbandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeadbandSpecified {
            get {
                return this.deadbandFieldSpecified;
            }
            set {
                this.deadbandFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int RequestedSamplingRate {
            get {
                return this.requestedSamplingRateField;
            }
            set {
                this.requestedSamplingRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RequestedSamplingRateSpecified {
            get {
                return this.requestedSamplingRateFieldSpecified;
            }
            set {
                this.requestedSamplingRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool EnableBuffering {
            get {
                return this.enableBufferingField;
            }
            set {
                this.enableBufferingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnableBufferingSpecified {
            get {
                return this.enableBufferingFieldSpecified;
            }
            set {
                this.enableBufferingFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
    public partial class WriteRequestItemList {
        
        private ItemValue[] itemsField;
        
        private string itemPathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items")]
        public ItemValue[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemPath {
            get {
                return this.itemPathField;
            }
            set {
                this.itemPathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
    public partial class OPCError {
        
        private string textField;
        
        private System.Xml.XmlQualifiedName idField;
        
        /// <remarks/>
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
    public partial class ReplyItemList {
        
        private ItemValue[] itemsField;
        
        private string reservedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items")]
        public ItemValue[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Reserved {
            get {
                return this.reservedField;
            }
            set {
                this.reservedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
    public partial class ReadRequestItem {
        
        private string itemPathField;
        
        private System.Xml.XmlQualifiedName reqTypeField;
        
        private string itemNameField;
        
        private string clientItemHandleField;
        
        private int maxAgeField;
        
        private bool maxAgeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemPath {
            get {
                return this.itemPathField;
            }
            set {
                this.itemPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName ReqType {
            get {
                return this.reqTypeField;
            }
            set {
                this.reqTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ClientItemHandle {
            get {
                return this.clientItemHandleField;
            }
            set {
                this.clientItemHandleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int MaxAge {
            get {
                return this.maxAgeField;
            }
            set {
                this.maxAgeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxAgeSpecified {
            get {
                return this.maxAgeFieldSpecified;
            }
            set {
                this.maxAgeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
    public partial class ReadRequestItemList {
        
        private ReadRequestItem[] itemsField;
        
        private string itemPathField;
        
        private System.Xml.XmlQualifiedName reqTypeField;
        
        private int maxAgeField;
        
        private bool maxAgeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items")]
        public ReadRequestItem[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemPath {
            get {
                return this.itemPathField;
            }
            set {
                this.itemPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName ReqType {
            get {
                return this.reqTypeField;
            }
            set {
                this.reqTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int MaxAge {
            get {
                return this.maxAgeField;
            }
            set {
                this.maxAgeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxAgeSpecified {
            get {
                return this.maxAgeFieldSpecified;
            }
            set {
                this.maxAgeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
    public partial class RequestOptions {
        
        private bool returnErrorTextField;
        
        private bool returnDiagnosticInfoField;
        
        private bool returnItemTimeField;
        
        private bool returnItemPathField;
        
        private bool returnItemNameField;
        
        private System.DateTime requestDeadlineField;
        
        private bool requestDeadlineFieldSpecified;
        
        private string clientRequestHandleField;
        
        private string localeIDField;
        
        public RequestOptions() {
            this.returnErrorTextField = true;
            this.returnDiagnosticInfoField = false;
            this.returnItemTimeField = false;
            this.returnItemPathField = false;
            this.returnItemNameField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool ReturnErrorText {
            get {
                return this.returnErrorTextField;
            }
            set {
                this.returnErrorTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ReturnDiagnosticInfo {
            get {
                return this.returnDiagnosticInfoField;
            }
            set {
                this.returnDiagnosticInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ReturnItemTime {
            get {
                return this.returnItemTimeField;
            }
            set {
                this.returnItemTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ReturnItemPath {
            get {
                return this.returnItemPathField;
            }
            set {
                this.returnItemPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ReturnItemName {
            get {
                return this.returnItemNameField;
            }
            set {
                this.returnItemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime RequestDeadline {
            get {
                return this.requestDeadlineField;
            }
            set {
                this.requestDeadlineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RequestDeadlineSpecified {
            get {
                return this.requestDeadlineFieldSpecified;
            }
            set {
                this.requestDeadlineFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ClientRequestHandle {
            get {
                return this.clientRequestHandleField;
            }
            set {
                this.clientRequestHandleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LocaleID {
            get {
                return this.localeIDField;
            }
            set {
                this.localeIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
    public partial class ServerStatus {
        
        private string statusInfoField;
        
        private string vendorInfoField;
        
        private string[] supportedLocaleIDsField;
        
        private interfaceVersion[] supportedInterfaceVersionsField;
        
        private System.DateTime startTimeField;
        
        private string productVersionField;
        
        /// <remarks/>
        public string StatusInfo {
            get {
                return this.statusInfoField;
            }
            set {
                this.statusInfoField = value;
            }
        }
        
        /// <remarks/>
        public string VendorInfo {
            get {
                return this.vendorInfoField;
            }
            set {
                this.vendorInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SupportedLocaleIDs")]
        public string[] SupportedLocaleIDs {
            get {
                return this.supportedLocaleIDsField;
            }
            set {
                this.supportedLocaleIDsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SupportedInterfaceVersions")]
        public interfaceVersion[] SupportedInterfaceVersions {
            get {
                return this.supportedInterfaceVersionsField;
            }
            set {
                this.supportedInterfaceVersionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProductVersion {
            get {
                return this.productVersionField;
            }
            set {
                this.productVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
    public enum interfaceVersion {
        
        /// <remarks/>
        XML_DA_Version_1_0,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
    public enum browseFilter {
        
        /// <remarks/>
        all,
        
        /// <remarks/>
        branch,
        
        /// <remarks/>
        item,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetStatusCompletedEventHandler(object sender, GetStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReplyBase Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReplyBase)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public ServerStatus Status {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServerStatus)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ReadCompletedEventHandler(object sender, ReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReplyBase Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReplyBase)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public ReplyItemList RItemList {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReplyItemList)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public OPCError[] Errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OPCError[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void WriteCompletedEventHandler(object sender, WriteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WriteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WriteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReplyBase Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReplyBase)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public ReplyItemList RItemList {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReplyItemList)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public OPCError[] Errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OPCError[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SubscribeCompletedEventHandler(object sender, SubscribeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubscribeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubscribeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReplyBase Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReplyBase)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public SubscribeReplyItemList RItemList {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SubscribeReplyItemList)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public OPCError[] Errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OPCError[])(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string ServerSubHandle {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SubscriptionPolledRefreshCompletedEventHandler(object sender, SubscriptionPolledRefreshCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubscriptionPolledRefreshCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubscriptionPolledRefreshCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReplyBase Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReplyBase)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string[] InvalidServerSubHandles {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public SubscribePolledRefreshReplyItemList[] RItemList {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SubscribePolledRefreshReplyItemList[])(this.results[2]));
            }
        }
        
        /// <remarks/>
        public OPCError[] Errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OPCError[])(this.results[3]));
            }
        }
        
        /// <remarks/>
        public bool DataBufferOverflow {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[4]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SubscriptionCancelCompletedEventHandler(object sender, SubscriptionCancelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubscriptionCancelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubscriptionCancelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string ClientRequestHandle {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void BrowseCompletedEventHandler(object sender, BrowseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BrowseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BrowseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReplyBase Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReplyBase)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string ContinuationPoint {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public BrowseElement[] Elements {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BrowseElement[])(this.results[2]));
            }
        }
        
        /// <remarks/>
        public OPCError[] Errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OPCError[])(this.results[3]));
            }
        }
        
        /// <remarks/>
        public bool MoreElements {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[4]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetPropertiesCompletedEventHandler(object sender, GetPropertiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPropertiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPropertiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReplyBase Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReplyBase)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public PropertyReplyList[] PropertyLists {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PropertyReplyList[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public OPCError[] Errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OPCError[])(this.results[2]));
            }
        }
    }
}

#pragma warning restore 1591